# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "abad629855a625bb632d2b8ea89c910c"
name = "Elko Connector"
application_url = "https://89.167.24.61"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,write_inventory,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
    "https://89.167.24.61/auth/callback",
    "https://89.167.24.61/auth/shopify/callback",
    "https://89.167.24.61/api/auth/callback"
  ]
